### ISSUE TITLE
Suggestion: Save canvas to png

### ISSUE THREAD

**Issue by bkw** [jsstyle/jsstyle.github.com#1]
... using sth. like http://www.nihilogic.dk/labs/canvas2image/

**Comment by ondras** [comment]
Yes, the whole <canvas> node can be actually replaced with an image with data: URI. On the other hand, good browsers offer "save image as" in canvas's context menu...

Anyway, this is a reasonable suggestion. Will investigate the size of the URI and probably implement it.
